= Gogs Operator

== Overview

This repository contains the code to build a Gogs Operator for Red Hat OpenShift Container Platform. It will not run on Kubernetes because it uses the `Route` object to provide access to Gogs.

The Operator will create a *PostgreSQL* database with persistent storage and a *Gogs Server* also with persistent storage connected to the PostgreSQL database.

It is implemented on top of the Red Hat https://github.com/operator-framework/operator-sdk[Operator SDK] - in particular the https://github.com/operator-framework/operator-sdk/blob/master/doc/ansible/user-guide.md[Ansible Operator].

== Installation

The installation of the Custom Resource Definition and Cluster Role requires *cluster-admin* privileges. After that regular users (who have been granted the *gogs-operator-depoyer* cluster role) can provision the Gogs Operator in their individual projects and deploy instances of Gogs using the gogs.gogs.opentlc.com Custom Resource.

. As *cluster-admin* deploy the Custom Resource Definition:
+
[source,sh]
----
oc create -f https://raw.githubusercontent.com/wkulhanek/gogs-operator/master/deploy/crds/gogs_v1alpha1_gogs_crd.yaml
----

. As *cluster-admin* deploy the Gogs Operator Deployer Cluster Role:
+
[source,sh]
----
oc create -f https://raw.githubusercontent.com/wkulhanek/gogs-operator/master/deploy/clusterrole.yaml
----

. As *cluster-admin* grant the gogs operator deployer cluster role to the user(s) that are allowed to create Gogs instances:
+
[source,sh]
----
oc adm policy add-cluster-role-to-user gogs-operator-deployer developer
----

. The next steps work either as *cluster-admin* or as a *regular user* (in the example above this is the user *developer*).
+
Create a new project in which to deploy Gogs:
+
[source,sh]
----
oc new-project gogs --display-name "Gogs Server"
----

. Deploy the *gogs-operator* service account:
+
[source,sh]
----
oc create -f https://raw.githubusercontent.com/wkulhanek/gogs-operator/master/deploy/service_account.yaml
----

. Deploy the *gogs-operator* role:
+
[source,sh]
----
oc create -f https://raw.githubusercontent.com/wkulhanek/gogs-operator/master/deploy/role.yaml
----

. Grant the *gogs-operator* role to the *gogs-operator* service account:
+
[source,sh]
----
oc create -f https://raw.githubusercontent.com/wkulhanek/gogs-operator/master/deploy/role_binding.yaml
----

. And finally create the Gogs *Operator*:
+
[source,sh]
----
oc create -f https://raw.githubusercontent.com/wkulhanek/gogs-operator/master/deploy/operator.yaml
----

. Once the Operator pod is running the Operator is ready to start creating Gogs Servers.

== Deploying a Gogs Server using the Operator

The Gogs Server is deployed by creating a Custom Resource based on the gogs Custom Resource Definition. There is an example of a Gogs CR at https://raw.githubusercontent.com/wkulhanek/gogs-operator/master/deploy/crds/gogs_v1alpha1_gogs_cr.yaml.

The Gogs Operator understands the following settings under it's *spec* setting:

* postgresqlVolumeSize: The size of the Persistent Volume to be created for the PostgreSQL database (e.g. 4Gi)
* postgresqlPort: The port for PostgreSQL to run under (e.g. 5432). Adjust if you want to run multiple instances of the Gogs CR in a single project
* gogsVolumeSize: The size of the Persistent Volume to be created for the Gogs database (e.g. 4Gi)

Example:
+
[source,texinfo]
----
apiVersion: gogs.opentlc.com/v1alpha1
kind: Gogs
metadata:
  name: gogs-server
spec:
  postgresqlVolumeSize: 4Gi
  postgresqlPort: 5432
  gogsVolumeSize: 4Gi
----

. Write the definition to a file (e.g. gogs-server.yaml) and then create the Gogs instance:
+
[source,sh]
----
oc create -f ./gogs-server.yaml
----

. The operator will first create the PostgreSQL database, wait until it is up and running and then create the Gogs Server.
. Validate that both pods (postgresql and gogs) are running before proceeding.
. Get the Route for the Gogs Server (the PostgreSQL database is not accessible outside of the project):
+
[source,sh]
----
oc get route
----

. Use the hostname returned in your Web Browser to open the Gogs UI.
